-
  name: Begin Installation
  hosts: all
  vars_files:
    - '{{ ansible_dir }}/{{ environment_name }}.yaml'
  user: ec2-user
  tasks:
    - name: Transfer the script directory
      copy: 'src={{ scripts_dir }} dest=/tmp mode=0755'
      become: yes
      become_user: tomcat
